# this is name of the workflow that will be display on the actions tab.
name: CICD

# Manual trigger workflow whenever user needed.
on:
  workflow_dispatch:

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code clone from github"
        
  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build docker container
        run: echo "Docker container build"
      
  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test the container
        run: echo "Test the container"
        
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deployed the app"
